baseURL = 'https://pikachuhya.github.io/'
languageCode = 'en-us'
title = "PikachuHy's Blog"
theme = 'ananke'

[params]
  toc = true
  custom_css = ["/css/custom.css"]

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight =  20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30
